### ISSUE TITLE
I am Benji

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/James#11]
![screen shot 2015-03-30 at 23 26 38](https://cloud.githubusercontent.com/assets/915130/6907177/408df234-d734-11e4-9553-ec0062973f97.png)

Pay up, Benji!

total price: €490.6

**Comment by feliciaan** [comment]
Please provide the steps to reproduce this bug.

**Comment by Silox** [comment]
1. I went in my browser to Foodbot
2. I was Benji

**Comment by becousae** [comment]
I have the same problem.

**Comment by feliciaan** [comment]
So you didn't login, and this was the first on the website?

**Comment by Silox** [comment]
`This was the first on the website`? Please speak english.

**Comment by FelixVanderJeugt** [comment]
I just followed @Silox's link, and ordered myself a middle pack on my own name (I could just fill in my name) using @becousae's account.

**Comment by feliciaan** [comment]
It happened because the database was cleared, but the secret key for encrypting the sessions were not changed. So @Silox' session contained information from the previous db, where @Silox had the same id as @becousae in the current db. Can be mitigated by modifying between new databases.

**Comment by Silox** [comment]
Or just never clear the database, as it shouldn't when we migitate to MySQL.
